# Generated by Django 5.2 on 2025-12-22 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('event', '0003_event_event_mode_event_meeting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Club organizing this event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clubs.club'),
        ),
    ]
