# Generated by Django 5.2 on 2025-12-22 04:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Club name', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly club identifier', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Club description')),
                ('club_type', models.CharField(choices=[('technical', 'Technical Club'), ('cultural', 'Cultural Club'), ('sports', 'Sports Club'), ('academic', 'Academic Club'), ('social', 'Social Club'), ('other', 'Other')], default='other', max_length=20)),
                ('email', models.EmailField(help_text='Official club email', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('website', models.URLField(blank=True, help_text='Club website URL')),
                ('logo', models.ImageField(blank=True, help_text='Club logo', null=True, upload_to='club_logos/')),
                ('banner', models.ImageField(blank=True, help_text='Club banner image', null=True, upload_to='club_banners/')),
                ('primary_color', models.CharField(default='#007bff', help_text='Primary brand color (hex code)', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Secondary brand color (hex code)', max_length=7)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Default club for the system')),
                ('allow_public_events', models.BooleanField(default=True, help_text='Allow public to view club events')),
                ('require_approval', models.BooleanField(default=False, help_text='Require admin approval for event creation')),
                ('payment_gateway', models.CharField(choices=[('cashfree', 'Cashfree'), ('payu', 'PayU')], default='cashfree', help_text='Default payment gateway for this club', max_length=20)),
                ('gateway_credentials', models.JSONField(blank=True, default=dict, help_text='Payment gateway credentials (JSON format)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Club Admin'), ('moderator', 'Moderator'), ('event_manager', 'Event Manager'), ('member', 'Member')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval')], default='active', max_length=20)),
                ('can_create_events', models.BooleanField(default=False)),
                ('can_manage_members', models.BooleanField(default=False)),
                ('can_manage_payments', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Club Membership',
                'verbose_name_plural': 'Club Memberships',
                'ordering': ['-joined_at'],
                'unique_together': {('club', 'user')},
            },
        ),
        migrations.AddField(
            model_name='club',
            name='admin_users',
            field=models.ManyToManyField(help_text='Users who can manage this club', related_name='administered_clubs', through='clubs.ClubMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClubSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_signature', models.TextField(blank=True, help_text='Email signature for club communications')),
                ('notification_emails', models.JSONField(blank=True, default=list, help_text='List of emails to receive notifications')),
                ('default_event_duration', models.PositiveIntegerField(default=120, help_text='Default event duration in minutes')),
                ('auto_approve_events', models.BooleanField(default=True, help_text='Auto-approve events created by members')),
                ('max_events_per_month', models.PositiveIntegerField(blank=True, help_text='Maximum events per month (optional)', null=True)),
                ('default_registration_deadline_days', models.PositiveIntegerField(default=1, help_text='Default registration deadline (days before event)')),
                ('allow_late_registration', models.BooleanField(default=False, help_text='Allow registration after deadline')),
                ('default_currency', models.CharField(default='INR', help_text='Default currency code', max_length=3)),
                ('payment_terms', models.TextField(blank=True, help_text='Payment terms and conditions')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Social media links (JSON format)')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Custom club-specific fields')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Club Settings',
                'verbose_name_plural': 'Club Settings',
            },
        ),
    ]
